appname = "goapirestway"
runmode = "prod"

[dev]
ds_mssql_taxi = "sqlserver://DevSQL:Sql.Dev.Pass@10.1.9.47:1433?database=TaxiVoucher&connection+timeout=30&encrypt=disable"
ds_mssql_mtdl = "sqlserver://DevSQL:Sql.Dev.Pass@10.1.9.47:1433?database=Metrodata&connection+timeout=30&encrypt=disable"
ds_mssql_bclm = "sqlserver://DevSQL:Sql.Dev.Pass@10.1.9.47:1433?database=PCVReimbursement&connection+timeout=30&&encrypt=disable"
ds_mssql_ptch = "sqlserver://DevSQL:Sql.Dev.Pass@10.1.9.47:1433?database=PettyCash&connection+timeout=30&&encrypt=disable"
ds_mssql_tra = "sqlserver://DevSQL:Sql.Dev.Pass@10.1.9.47:1433?database=TRA&connection+timeout=30&&encrypt=disable"
ds_psql_dochr = "user=documentsnumberhrduser password=17Sudirman host=127.0.0.1 port=5432 dbname=documentsnumberhrd sslmode=disable"
ds_psql_gar_url = "user=goapirestwayuser password=17gOapirestwAy45 host=127.0.0.1 port=5432 dbname=mone sslmode=disable"
ds_psql_gar_host = "127.0.0.1"
ds_psql_gar_port = "5432"
ds_psql_gar_user = "goapirestwayuser"
ds_psql_gar_pass = "17gOapirestwAy45"
ds_psql_gar_name = "mone"
ds_psql_gar_schema = "mone"
ds_psql_admin_user = "postgres"
ds_psql_admin_pass = "17Sudirman"
ds_psql_admin_schema = "template1"
ds_sqlite = "db/goapirestway.db"
log_path = "log"
log_filename = "goapirestway.log"
log_maxsize = 100 #100MB
log_maxbackup = 128 #files
log_maxage = 14 #days
file_path = "files"
file_logging = true
console_logging = true
jsonLogOutput = true
log_path_windows = "C:\\tmp\\goapirestway\\logs"
file_path_windows = "C:\\tmp\\goapirestway\\files"
logging_level = "DEBUG"
port_api = ":9191"
map_api="AIzaSyDpNC8Oby67HQo0AzrMxCUPunsxSElLxDE"
seaweed_url="http://172.16.0.62:9333"
seaweed_img_url="img.synnexmetrodata.com"
qr_output_path="./files/output/"
smb_server="10.1.10.68:445"
smb_share="hrd"
smb_user="hrd"
smb_pass="10aplHrd"
smb_domain="Metrodata"
sftp_sf_host="52.187.20.4:22"
sftp_sf_user="sftpuser"
sftp_sf_pass="Soltius.1"
sftp_sf_path="/SuccessFactors/General"
sap_host="172.41.2.61"
sap_user="sapwf"
sap_pwd="misdev.8"
sap_sysnr="20"
sap_client="400"

[prod]
ds_mssql_taxi = "sqlserver://TaxiServices:Txv_41@mtrdb20.metrodata.co.id:1433?database=TaxiVoucher&connection+timeout=30&TrustServerCertificate=true"
ds_mssql_mtdl = "sqlserver://TaxiServices:Txv_41@mtrdb20.metrodata.co.id:1433?database=Metrodata&connection+timeout=30&TrustServerCertificate=true"
ds_mssql_bclm = "sqlserver://PCVUser:pcvreimbursement_41@mtrdb20.metrodata.co.id:1433?database=PCVReimbursement&connection+timeout=30&TrustServerCertificate=true"
ds_mssql_ptch = "sqlserver://PCVUser:pcvreimbursement_41@mtrdb20.metrodata.co.id:1433?database=PettyCash&connection+timeout=30&TrustServerCertificate=true"
ds_mssql_tra = "sqlserver://TRA_User:metrodata.11@mtrdb20.metrodata.co.id:1433?database=TRA&connection+timeout=30&TrustServerCertificate=true"
ds_psql_dochr= "user=documentsnumberhrduser password=D@cum3ntHrD host=ocean.synnexmetrodata.com port=5432 dbname=documentsnumberhrd sslmode=disable"
ds_psql_gar_url = "user=goapirestwayuser password=gOapiRestway19 host=ocean.synnexmetrodata.com port=5432 dbname=goapirestway sslmode=disable"
ds_psql_gar_host = "ocean.synnexmetrodata.com"
ds_psql_gar_port = "5432"
ds_psql_gar_user = "goapirestwayuser"
ds_psql_gar_pass = "gOapiRestway19"
ds_psql_gar_name = "goapirestway"
ds_psql_gar_schema = "mone"
ds_psql_admin_user = "postgres"
ds_psql_admin_pass = "bEngawansolO#548"
ds_psql_admin_schema = "template1"
ds_sqlite = "db/goapirestway.db"
log_path = "/var/log/goapirestway/"
log_filename = "goapirestway.log"
log_maxsize = 100 #100MB
log_maxbackup = 128 #files
log_maxage = 14 #days
file_path = "files"
file_logging = true
console_logging = true
jsonLogOutput = true
log_path_windows = "C:\\tmp\\goapirestway\\log"
file_path_windows = "C:\\tmp\\goapirestway\\files"
logging_level = "INFO"
port_api = ":9192"
map_api="AIzaSyDpNC8Oby67HQo0AzrMxCUPunsxSElLxDE"
seaweed_url="http://172.16.0.62:9333"
seaweed_img_url="img.synnexmetrodata.com"
qr_output_path="./files/output/"
smb_server="10.1.10.68:445"
smb_share="hrd"
smb_user="hrd"
smb_pass="10aplHrd"
smb_domain="Metrodata"
sftp_sf_host="52.187.20.4:22"
sftp_sf_user="sftpuser"
sftp_sf_pass="Soltius.1"
sftp_sf_path="/SuccessFactors/General"
sap_host="172.41.7.30"
sap_user="SAPWF"
sap_pwd="METRO.0052"
sap_sysnr="50"
sap_client="400"