appname = "clothingretail"
runmode = "dev"

[dev]
ds_sqlite = "db/clothingretail_dev.db"
log_path = "log"
log_filename = "clothingretail_dev.log"
log_maxsize = 100 #100MB
log_maxbackup = 128 #files
log_maxage = 14 #days
file_path = "files"
file_logging = true
console_logging = true
jsonLogOutput = true
log_path_windows = "C:\\tmp\\clothingretail\\logs"
file_path_windows = "C:\\tmp\\clothingretail\\files"
logging_level = "DEBUG"
port_api = ":9120"
seaweed_url="http://172.16.0.62:9333"
seaweed_img_url="img.synnexmetrodata.com"
qr_output_path="./files/output/"

[prod]
ds_sqlite = "db/clothingretail.db"
log_path = "/var/log/clothingretail/"
log_filename = "goapirestway.log"
log_maxsize = 100 #100MB
log_maxbackup = 128 #files
log_maxage = 14 #days
file_path = "files"
file_logging = true
console_logging = true
jsonLogOutput = true
log_path_windows = "C:\\tmp\\clothingretail\\log"
file_path_windows = "C:\\tmp\\clothingretail\\files"
logging_level = "INFO"
port_api = ":9121"
seaweed_url="http://172.16.0.62:9333"
seaweed_img_url="img.synnexmetrodata.com"
qr_output_path="./files/output/"