package utils

const (
	CAT_STATUS_ACTIVE   int = 1
	CAT_STATUS_INACTIVE int = 2

	CAT_STATUS_ACTIVE_STR   string = "ACTIVE"
	CAT_STATUS_INACTIVE_STR string = "INACTIVE"

	CAT_SUB_STATUS_ACTIVE       int    = 1
	CAT_SUB_STATUS_INACTIVE     int    = 2
	CAT_SUB_STATUS_ACTIVE_STR   string = "ACTIVE"
	CAT_SUB_STATUS_INACTIVE_STR string = "INACTIVE"

	CAT_CUST_STATUS_ACTIVE       int    = 1
	CAT_CUST_STATUS_INACTIVE     int    = 2
	CAT_CUST_STATUS_ACTIVE_STR   string = "ACTIVE"
	CAT_CUST_STATUS_INACTIVE_STR string = "INACTIVE"

	CLOTHES_SIZE_STATUS_ACTIVE       int    = 1
	CLOTHES_SIZE_STATUS_INACTIVE     int    = 2
	CLOTHES_SIZE_STATUS_ACTIVE_STR   string = "ACTIVE"
	CLOTHES_SIZE_STATUS_INACTIVE_STR string = "INACTIVE"

	CLOTHES_MOV_ACTION_BUY        int = 1
	CLOTHES_MOV_ACTION_SELL       int = 2
	CLOTHES_MOV_ACTION_RENT       int = 3
	CLOTHES_MOV_ACTION_RETURN     int = 4
	CLOTHES_MOV_ACTION_NOT_RETURN int = 5
	CLOTHES_MOV_ACTION_WRITE_OFF  int = 6
	CLOTHES_MOV_ACTION_LOST       int = 7

	CLOTHES_MOV_ACTION_BUY_STR        string = "BUY"
	CLOTHES_MOV_ACTION_SELL_STR       string = "SELL"
	CLOTHES_MOV_ACTION_RENT_STR       string = "RENT"
	CLOTHES_MOV_ACTION_RETURN_STR     string = "RETURN"
	CLOTHES_MOV_ACTION_NOT_RETURN_STR string = "NOT RETURN"
	CLOTHES_MOV_ACTION_WRITE_OFF_STR  string = "WRITE OFF"
	CLOTHES_MOV_ACTION_LOST_STR       string = "LOST"

	CLOTHES_RENT_STATUS_RENTED     int = 1
	CLOTHES_RENT_STATUS_RETURN     int = 2
	CLOTHES_RENT_STATUS_CANCEL     int = 3
	CLOTHES_RENT_STATUS_NOT_RETURN int = 4
	CLOTHES_RENT_STATUS_LOSS       int = 5

	CLOTHES_RENT_STATUS_RENTED_STR     string = "RENTED"
	CLOTHES_RENT_STATUS_RETURN_STR     string = "RETURN"
	CLOTHES_RENT_STATUS_CANCEL_STR     string = "CANCEL"
	CLOTHES_RENT_STATUS_NOT_RETURN_STR string = "NOT RETURN"
	CLOTHES_RENT_STATUS_LOSS_STR       string = "LOSS"

	CLOTHES_USER_STATUS_ACTIVE    int = 1
	CLOTHES_USER_STATUS_INACTIVE  int = 2
	CLOTHES_USER_STATUS_SUSPENDED int = 3

	CLOTHES_USER_STATUS_ACTIVE_STR    string = "ACTIVE"
	CLOTHES_USER_STATUS_INACTIVE_STR  string = "INACTIVE"
	CLOTHES_USER_STATUS_SUSPENDED_STR string = "SUSPENDED"
)

func CatTrans(status int) string {
	switch status {
	case CAT_STATUS_ACTIVE:
		return CAT_STATUS_ACTIVE_STR
	case CAT_STATUS_INACTIVE:
		return CAT_STATUS_INACTIVE_STR
	}
	return ""
}

func CatTransReverse(status string) int {
	switch status {
	case CAT_STATUS_ACTIVE_STR:
		return CAT_STATUS_ACTIVE
	case CAT_STATUS_INACTIVE_STR:
		return CAT_STATUS_INACTIVE
	}
	return 0
}

func CatMap() map[int]string {
	return map[int]string{
		CAT_STATUS_ACTIVE:   CAT_STATUS_ACTIVE_STR,
		CAT_STATUS_INACTIVE: CAT_STATUS_INACTIVE_STR,
	}
}

func CatSubTrans(status int) string {
	switch status {
	case CAT_SUB_STATUS_ACTIVE:
		return CAT_SUB_STATUS_ACTIVE_STR
	case CAT_SUB_STATUS_INACTIVE:
		return CAT_SUB_STATUS_INACTIVE_STR
	}
	return ""
}

func CatSubTransReverse(status string) int {
	switch status {
	case CAT_SUB_STATUS_ACTIVE_STR:
		return CAT_SUB_STATUS_ACTIVE
	case CAT_SUB_STATUS_INACTIVE_STR:
		return CAT_SUB_STATUS_INACTIVE
	}
	return 0
}

func CatSubMap() map[int]string {
	return map[int]string{
		CAT_SUB_STATUS_ACTIVE:   CAT_SUB_STATUS_ACTIVE_STR,
		CAT_SUB_STATUS_INACTIVE: CAT_SUB_STATUS_INACTIVE_STR,
	}
}

func CatCustTrans(status int) string {
	switch status {
	case CAT_CUST_STATUS_ACTIVE:
		return CAT_CUST_STATUS_ACTIVE_STR
	case CAT_CUST_STATUS_INACTIVE:
		return CAT_CUST_STATUS_INACTIVE_STR
	}
	return ""
}

func CatCustTransReverse(status string) int {
	switch status {
	case CAT_CUST_STATUS_ACTIVE_STR:
		return CAT_CUST_STATUS_ACTIVE
	case CAT_CUST_STATUS_INACTIVE_STR:
		return CAT_CUST_STATUS_INACTIVE
	}
	return 0
}

func CatCustMap() map[int]string {
	return map[int]string{
		CAT_CUST_STATUS_ACTIVE:   CAT_CUST_STATUS_ACTIVE_STR,
		CAT_CUST_STATUS_INACTIVE: CAT_CUST_STATUS_INACTIVE_STR,
	}
}

func ClothesSizeTrans(status int) string {
	switch status {
	case CLOTHES_SIZE_STATUS_ACTIVE:
		return CLOTHES_SIZE_STATUS_ACTIVE_STR
	case CLOTHES_SIZE_STATUS_INACTIVE:
		return CLOTHES_SIZE_STATUS_INACTIVE_STR
	}
	return ""
}

func ClothesSizeTransReverse(status string) int {
	switch status {
	case CLOTHES_SIZE_STATUS_ACTIVE_STR:
		return CLOTHES_SIZE_STATUS_ACTIVE
	case CLOTHES_SIZE_STATUS_INACTIVE_STR:
		return CLOTHES_SIZE_STATUS_INACTIVE
	}
	return 0
}

func ClothesSizeMap() map[int]string {
	return map[int]string{
		CLOTHES_SIZE_STATUS_ACTIVE:   CLOTHES_SIZE_STATUS_ACTIVE_STR,
		CLOTHES_SIZE_STATUS_INACTIVE: CLOTHES_SIZE_STATUS_INACTIVE_STR,
	}
}

func ClothesMovActionTrans(status int) string {
	switch status {
	case CLOTHES_MOV_ACTION_BUY:
		return CLOTHES_MOV_ACTION_BUY_STR
	case CLOTHES_MOV_ACTION_SELL:
		return CLOTHES_MOV_ACTION_SELL_STR
	case CLOTHES_MOV_ACTION_RENT:
		return CLOTHES_MOV_ACTION_RENT_STR
	case CLOTHES_MOV_ACTION_RETURN:
		return CLOTHES_MOV_ACTION_RETURN_STR
	case CLOTHES_MOV_ACTION_NOT_RETURN:
		return CLOTHES_MOV_ACTION_NOT_RETURN_STR
	case CLOTHES_MOV_ACTION_WRITE_OFF:
		return CLOTHES_MOV_ACTION_WRITE_OFF_STR
	case CLOTHES_MOV_ACTION_LOST:
		return CLOTHES_MOV_ACTION_LOST_STR
	}
	return ""
}

func ClothesMovActionTransReverse(status string) int {
	switch status {
	case CLOTHES_MOV_ACTION_BUY_STR:
		return CLOTHES_MOV_ACTION_BUY
	case CLOTHES_MOV_ACTION_SELL_STR:
		return CLOTHES_MOV_ACTION_SELL
	case CLOTHES_MOV_ACTION_RENT_STR:
		return CLOTHES_MOV_ACTION_RENT
	case CLOTHES_MOV_ACTION_RETURN_STR:
		return CLOTHES_MOV_ACTION_RETURN
	case CLOTHES_MOV_ACTION_NOT_RETURN_STR:
		return CLOTHES_MOV_ACTION_NOT_RETURN
	case CLOTHES_MOV_ACTION_WRITE_OFF_STR:
		return CLOTHES_MOV_ACTION_WRITE_OFF
	case CLOTHES_MOV_ACTION_LOST_STR:
		return CLOTHES_MOV_ACTION_LOST
	}
	return 0
}

func ClothesMovActionMap() map[int]string {
	return map[int]string{
		CLOTHES_MOV_ACTION_BUY:        CLOTHES_MOV_ACTION_BUY_STR,
		CLOTHES_MOV_ACTION_SELL:       CLOTHES_MOV_ACTION_SELL_STR,
		CLOTHES_MOV_ACTION_RENT:       CLOTHES_MOV_ACTION_RENT_STR,
		CLOTHES_MOV_ACTION_RETURN:     CLOTHES_MOV_ACTION_RETURN_STR,
		CLOTHES_MOV_ACTION_NOT_RETURN: CLOTHES_MOV_ACTION_NOT_RETURN_STR,
		CLOTHES_MOV_ACTION_WRITE_OFF:  CLOTHES_MOV_ACTION_WRITE_OFF_STR,
		CLOTHES_MOV_ACTION_LOST:       CLOTHES_MOV_ACTION_LOST_STR,
	}
}

func ClothesRentStatusTrans(status int) string {
	switch status {
	case CLOTHES_RENT_STATUS_RENTED:
		return CLOTHES_RENT_STATUS_RENTED_STR
	case CLOTHES_RENT_STATUS_RETURN:
		return CLOTHES_RENT_STATUS_RETURN_STR
	case CLOTHES_RENT_STATUS_CANCEL:
		return CLOTHES_RENT_STATUS_CANCEL_STR
	case CLOTHES_RENT_STATUS_NOT_RETURN:
		return CLOTHES_RENT_STATUS_NOT_RETURN_STR
	case CLOTHES_RENT_STATUS_LOSS:
		return CLOTHES_RENT_STATUS_LOSS_STR
	}
	return ""
}

func ClothesRentStatusTransReverse(status string) int {
	switch status {
	case CLOTHES_RENT_STATUS_RENTED_STR:
		return CLOTHES_RENT_STATUS_RENTED
	case CLOTHES_RENT_STATUS_RETURN_STR:
		return CLOTHES_RENT_STATUS_RETURN
	case CLOTHES_RENT_STATUS_CANCEL_STR:
		return CLOTHES_RENT_STATUS_CANCEL
	case CLOTHES_RENT_STATUS_NOT_RETURN_STR:
		return CLOTHES_RENT_STATUS_NOT_RETURN
	case CLOTHES_RENT_STATUS_LOSS_STR:
		return CLOTHES_RENT_STATUS_LOSS
	}
	return 0
}

func ClothesRentStatusMap() map[int]string {
	return map[int]string{
		CLOTHES_RENT_STATUS_RENTED:     CLOTHES_RENT_STATUS_RENTED_STR,
		CLOTHES_RENT_STATUS_RETURN:     CLOTHES_RENT_STATUS_RETURN_STR,
		CLOTHES_RENT_STATUS_CANCEL:     CLOTHES_RENT_STATUS_CANCEL_STR,
		CLOTHES_RENT_STATUS_NOT_RETURN: CLOTHES_RENT_STATUS_NOT_RETURN_STR,
		CLOTHES_RENT_STATUS_LOSS:       CLOTHES_RENT_STATUS_LOSS_STR,
	}
}

func ClothesUserStatusTrans(status int) string {
	switch status {
	case CLOTHES_USER_STATUS_ACTIVE:
		return CLOTHES_USER_STATUS_ACTIVE_STR
	case CLOTHES_USER_STATUS_INACTIVE:
		return CLOTHES_USER_STATUS_INACTIVE_STR
	case CLOTHES_USER_STATUS_SUSPENDED:
		return CLOTHES_USER_STATUS_SUSPENDED_STR
	}
	return ""
}

func ClothesUserStatusTransReverse(status string) int {
	switch status {
	case CLOTHES_USER_STATUS_ACTIVE_STR:
		return CLOTHES_USER_STATUS_ACTIVE
	case CLOTHES_USER_STATUS_INACTIVE_STR:
		return CLOTHES_USER_STATUS_INACTIVE
	case CLOTHES_USER_STATUS_SUSPENDED_STR:
		return CLOTHES_USER_STATUS_SUSPENDED
	}
	return 0
}

func ClothesUserStatusMap() map[int]string {
	return map[int]string{
		CLOTHES_USER_STATUS_ACTIVE:    CLOTHES_USER_STATUS_ACTIVE_STR,
		CLOTHES_USER_STATUS_INACTIVE:  CLOTHES_USER_STATUS_INACTIVE_STR,
		CLOTHES_USER_STATUS_SUSPENDED: CLOTHES_USER_STATUS_SUSPENDED_STR,
	}
}
